version: '2'
services:
  to-backup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADV_HOST=to-backup
      - FORWARDLOGS=0
      - RUNTESTS=0
    volumes:
      - "../../build/libs/kafka-backup.jar:/connectors/kafka-backup.jar"
      - "./utils.sh:/root/utils.sh"
      - "./runutil:/bin/runutil"
      - "./tmp/:/kafka-backup/:rw"
  restore-to:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADV_HOST=restore-to
      - FORWARDLOGS=0
      - RUNTESTS=0
    volumes:
      - "../../build/libs/kafka-backup.jar:/connectors/kafka-backup.jar"
      - "./utils.sh:/root/utils.sh"
      - "./runutil:/bin/runutil"
      - "./profile-utils:/etc/profile.d/profile-utils"
      - "./tmp/:/kafka-backup/:rw"